name: Bot
on:
  issue_comment:
    types: created

jobs:
  commented:
    name: Copy comment to open PRs
    if: github.event.issue.number == 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GIT_AUTHOR_NAME: matticbot
          GIT_AUTHOR_EMAIL: matticbot@users.noreply.github.com
          GIT_COMMITTER_NAME: matticbot
          GIT_COMMITTER_EMAIL: matticbot@users.noreply.github.com
          DATA: ${{ toJson( github.event.comment ) }}
          TOKEN: ${{ github.token }}
        run: |
          git fetch
          for BRANCH in $(curl --fail --get --header "authorization: Bearer $TOKEN" "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls?state=open&per_page=100" | jq -r '.[].head.ref'); do
            git checkout "$BRANCH"
            echo "$DATA" > comment.json
            git add comment.json
            git commit -m 'Update comment'
            git push
          done
